### ISSUE TITLE
continuous Restarting server message appears on the console

### ISSUE THREAD

**Issue by serkandemirhan** [KarimJedda/whatsappcli#12]
On windows 10 64bit instalaltion 
Firstlt I get  following errors 

/*******************
E:\whatsapp>python27 whatsappcli/src/server.py
Traceback (most recent call last):
  File "whatsappcli/src/server.py", line 13, in <module>
    from router import RouteLayer
  File "E:\whatsapp\whatsappcli\src\router.py", line 12, in <module>
    from routes import MediaViews
  File "E:\whatsapp\whatsappcli\src\routes.py", line 2, in <module>
    from src.utils.memReport import memReport
ImportError: No module named src.utils.memReport
**********************************/

then I removed the src text words from routes.py they are as follows:

/************** src/routes.py transformed followin lines 
from  utils.memReport import memReport
from utils.media_downloader import ImageSender, VideoSender, YoutubeSender, UrlPrintSender, 
********************/

Then I am having the following output and it does not work

_server.py_     [INFO][2017-03-28 12:38:19,233] Restarting..
_server.py_     [INFO][2017-03-28 12:38:19,250] ##################################################
_server.py_     [INFO][2017-03-28 12:38:19,250] Server started. Phone number: 905533148914
_server.py_     [INFO][2017-03-28 12:38:19,250] ##################################################
_server.py_     [INFO][2017-03-28 12:38:19,681] Restarting..
_server.py_     [INFO][2017-03-28 12:38:19,681] ##################################################
_server.py_     [INFO][2017-03-28 12:38:19,681] Server started. Phone number: 905533148914
_server.py_     [INFO][2017-03-28 12:38:19,681] ##################################################
_server.py_     [INFO][2017-03-28 12:38:20,119] Restarting..
_server.py_     [INFO][2017-03-28 12:38:20,134] ##################################################
_server.py_     [INFO][2017-03-28 12:38:20,134] Server started. Phone number: 905533148914
_server.py_     [INFO][2017-03-28 12:38:20,134] ##################################################
_server.py_     [INFO][2017-03-28 12:38:20,566] Restarting..

*************///
What is going wrond about this?

**Comment by maykbrito** [comment]
Same error here.. I deleted the "src" part of "src.utils..."
