### ISSUE TITLE
memoryUsage Error

### ISSUE THREAD

**Issue by peppeska** [KarimJedda/whatsappcli#6]
when i send memoryUsage command:

```
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/peppeska/Scaricati/whatsappcli/src/router.py", line 35, in route
    data = callback(message, match)
  File "/home/peppeska/Scaricati/whatsappcli/src/routes.py", line 40, in memory_usage
    output = memReport()
  File "/home/peppeska/Scaricati/whatsappcli/src/utils/memReport.py", line 9, in memReport
    vm = subprocess.Popen(['vm_stat'], stdout=subprocess.PIPE).communicate()[0]
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by peppeska** [comment]
ok..
on Arch LInux vm_stat is vmstat ;)
